### PR TITLE
Add ability to use fabfile.yaml.inc + fixing directory traversal and merging multiple yaml configurations

### PR DESCRIPTION
**Pull request by MuschPusch**
First one is easy: fabfile.yaml.inc will also be parsed with the benefit that those files aren't served by webservers.

Second is a bit more complex. Fabalicious will traverse two directories up when looking for yaml configuration files and will merge the configuration files found. The idea behind this is to add a default docker fabfile.yaml to the multibasebox with all 'default' docker tasks. Right now we define hproxy reload, run etc in every project. This removes some code duplication in the yaml files and will make it easier to create a new configurations. I will add a branch to multibasebox with a yaml file.

(I started stupid because i started working on master and merged back my changes to develop for this pull requests. Don't ask me why but some of your commits on master have never made it to develop those are included now... )

### CODE REVIEW

**Comment by stmh** [comment]
I think we need another approach, because:

* fabfile.py will still be served by apache (ok, no vulnerable data)
* inc-files are only forbidden for drupal-installations (see .htaccess)
* the inc-extension is a bit misleading
* the existing directory-traversal was in place to enable the usage of fabalicious outside the root-directory (e.g. from the theme-folder)
* the docker.configuration should be part of the project and not part of the multibasebox, as the multibasebox should be agnostic how you manage your docker-instances. E.g. the example-fabfile will not work für middleman-based installations.

I agree with you that we have a lot of copy-paste-stuff across our projects and we should find a way to include common configuration into a fabfile. Moving configuration out of the git-repositories will make it harder for other people to get up and running with a project, as they have to gather all needed config files from other places.

I'd like to have a mechanism to include configuration from a specific folder or even from a http-address. So we can set up the docker-configuration for a host like this:

```
hosts:
  - mbb:
      ...
     docker:
         configuration: ../../fabalicious/mbb-drupal-docker.yml
  - a.remote.host.de:
    docker:
      configuration: http://a.public.host/a-remote-host-de-docker.yml

```

What do you think?

**Comment by stmh** [comment]
And what I also want to implement (I have already some code for this:)

```.
fabalicious
├── dockerHosts
│   ├── default.yaml
│   ├── local.yaml
│   ├── mbb.yaml
│   └── dev-server.yaml
├── hosts
│   ├── stage.host.server2.de.yaml
│   ├── local.yaml
│   ├── mbb.yaml
│   ├── platnum-live.yaml
│   └── dev.host.server2.de.yaml
└── index.yaml
```

**Comment by MuschPusch** [comment]
- fabfile.py will still be served by apache (ok, no vulnerable data)

it's on github too and some script kiddies can download it from client servers if they want to :)

- inc-files are only forbidden for drupal-installations (see .htaccess)

Agreed when we move the fabfile to a subfolder we could add a .htaccess for apache.

- the inc-extension is a bit misleading

Would be still in favor for this until it's done right. Updating drupal makes the fabfiles accessible right now. A bad configured database server would be vulnerable. 

- the existing directory-traversal was in place to enable the usage of fabalicious outside the root-directory (e.g. from the theme-folder)

I have no idea how that code works but it works differently than you think. Calling current fabalicious will traverse in our projects like this:

_tools/fabalicious
_tools/
projectRoot 

- the docker.configuration should be part of the project and not part of the multibasebox, as the multibasebox should be agnostic how you manage your docker-instances. E.g. the example-fabfile will not work für middleman-based installations.

The initial idea was to lower the burden to create a new project and avoid code duplication. We could create different docker presets for middleman, drupal, kirby etc. In the end it's up the user which 'preset' he will inherit from in his yaml file. At the same time we will have more control to change global configuration. If you don't want to have it in the multibasebox where else should we put it?


Regarding the file structure: 

I like it! What's the purpose of index.yaml? I'm not sure if i like seperating the dockerHosts from the hosts. When having a good docker presets the docker host for mbb would be just something this or not?

    mbb.yaml
      inheritsFrom: drupal
      host: testing.dev

**Comment by stmh** [comment]
we should discuss this in RL ;-)

**Comment by stmh** [comment]
Please have a look at the feature-branch feature/includes. It allows inclusion of external files for docker-configuration and for inheritsFrom. You can use inheritsFrom even on the root-level of the fabfile.yaml (I added some documentation to the Readme)

This should resemble your pull request (even fabfile.yaml.inc) but in a more generalized way without the implicit knowledge of how directories got traversed. 

This is still alpha-quality-code and basebox and multibasebox needs to be ported over, but it looks really powerful to me. 

We should discuss this on Monday or so.

**Comment by stmh** [comment]
Closing this for now, as the required functionality is now part of the develop-branch

**Pull request closed without merging**
